spring.application.name=OrderingFood


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/orderingfood
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

orderingfood.jwt.base64-secret=aGt+l495xiSEUkVSDYyuaQDPm8Emb//pk7+SUpUaAjM=
orderingfood.jwt.access-token-validity-in-seconds=86400000
orderingfood.jwt.refresh-token-validity-in-seconds=86400000

#false: start with 0; true: start with 1
spring.data.web.pageable.one-indexed-parameters=true

file.upload-dir=D:\\datafileFood
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB